export const routeKey = {
    home: '/',
    login: '/login',
    signup: '/register',
    detailPost: '/post/detail/:id',
    profile: '/profile/user/:userId',
    detailTour: '/tour/:id',
    ListPost: '/posts',
    profileUser: '/profile/business/:userId',
    cart: '/cart',
    payment: '/payment',
    forgotPass: '/forgot',
    searchPage: '/search',
    chat: '/app/chat',
    feedBack: '/feedBack',
    policy: '/policy',
    help: '/help',
    friend: 'friend',
};
